#!/usr/bin/env bash
#
# Función que copia el archivo de posición trampas a la carpeta validación_datapackage para que sea
# validado
dest_path=data/validacion_datapackage
mkdir ${dest_path} --parents
position_traps_data_file=${1}
file_name=$(basename "${position_traps_data_file}")
src_path=$(dirname "${position_traps_data_file}")
cp ${position_traps_data_file} ${src_path} ${dest_path}
