#!/usr/bin/env bash
#
#Función para contar capturas en posicion_trampas por zona
first_file=${1}
first_table=$(basename "${first_file}" .csv)
csvsql --snifflimit 0 --no-inference --blanks --query \
"SELECT
    CASE 
    WHEN ID_de_trampa = 'NA' THEN 'NA'
    ELSE SUBSTR(ID_de_trampa,1,2)
  END Tipo_de_trampa,
  CASE 
    WHEN ID_de_trampa = 'NA' THEN 'NA'
    ELSE SUBSTR(ID_de_trampa,4,2)
  END Zona,
  COUNT(*) AS Capturas_totales
FROM ${first_table}
WHERE Estado_trampa = 'X'
GROUP BY Zona, Tipo_de_trampa
" ${first_file}