#!/usr/bin/env bash
#
position_trap_file_name_xlsx=${1}
position_trap_data_path=$(direname ${file_name_xlsx})
position_trap_data_file=${data_path}/$(basename ${file_name_xlsx} .xlsx)
src_path="src"
# Revisión estructural de la tabla posición trampa
# 1. Recibimos los datos
# 2. Encontrar duplicados
	${src_path}/distinct_position_traps ${position_trap_file_name_xlsx}
# 3. Revisar nombres de las columnas
	${src_path}/make_check_header.R --data ${position_trap_data_file}.csv
# 4. Validacion con datapackage
  #Cambiamos el encabezado y movemos el archivo a la carpeta que contiene el datapackage.json para
  #correr ahí el goodtables
	${src_path}/change_header ${position_trap_data_file}.csv
exit
# 5. Cambia archivo 'posición trampas' a la carpeta 'validación datapackage'



# Revisa y compara las capturas de los archivos posición trampas y morfometría gatos
# 5. Hacerlos tidy (feature/agrega_script_con_cli)
	src/make_table_tidy.R \
	--data ${position_trap_data_file}.csv \
	--salida ${position_trap_data_file}_tidy.csv
# 6. Limpiar archivos
# 6.1 Morfometría
# Tiene que ser la salida de la funcion cambia formato_fecha (ISO8601)
	src/clean_morphometry.R \
    	--data=data/raw/morfometria_gatos_erradicacion_isla_guadalupe_ISO8601.csv \
    	--out=reports/tables/cleaned_morphometry_cats.csv
# 6.2 Posición trampa
	src/get_captures.R \
		--data=IG_POSICION_TRAMPAS_10MAY2020_tidy.csv \
		--out=reports/tables/cleaned_position_traps.csv
# 7. Comparar morfometría con posicion (Capturas que no están en morfometría)
# 	>$@ Salida estándar
    src/show_diff_morphometry_position.R \
		--data_1=reports/tables/cleaned_position_traps.csv \
		--data_2=reports/tables/cleaned_morphometry_cats.csv \
		> missing_captures_in_position.csv
# 8. Comparar posicion con morfometría (Capturas que no están en posición)
    src/show_diff_morphometry_position.R \
		--data_1=reports/tables/cleaned_morphometry_cats.csv \
        --data_2=reports/tables/cleaned_position_traps.csv \
		> missing_captures_in_morfometry.csv
# 9. Consignamos (pre-commit)
	# El precommit verifica que los archivos missing_captures_in_position.csv y 
	# missing_captures_in_morfometry estén vacios para poder consignar IG_POSICION_TRAMPAS_10MAY2020.csv

# 10. Query para separar por zonas

# 11. Sacamos resumen

# 12. Agregar resumen semanal a base de datos mayor