#!/usr/bin/env bash
#
# Detecta ID duplicados de la tabla de posicion_trampas
# El archivo de entrada es .xlsx y se obtiene un .csv con los ID duplicados
data_file=${1}
src_path=$(dirname "${data_file}")
table_name=$(basename "${data_file}" .xlsx)
in2csv --no-header-row --blanks ${data_file} | tail --lines=+2 > ${src_path}/${table_name}.csv
csvsql --snifflimit 0 --no-inference --blanks --query "
  SELECT *
  FROM ${table_name}
  WHERE ID IN (
    SELECT ID
    FROM ${table_name}
    GROUP BY ID
    HAVING COUNT(*) > 1)
  ORDER BY ID
" ${src_path}/${table_name}.csv 
