#!/usr/bin/env bash
#
#Quita registros de posicion de trampas con base que no están en la tabla de morfometría
first_file=${1}
second_file=${2}
first_table=$(basename "${first_file}" .csv)
second_table=$(basename "${second_file}" .csv)
csvsql --snifflimit 0 --no-inference --blanks --query \
"SELECT *
FROM ${first_table}
WHERE (ID_de_trampa,Fecha) NOT IN (
      SELECT ID_de_trampa, Fecha
      FROM ${second_table})
" ${first_file} ${second_file} > posicion_trampas_gatos_isla_guadalupe_sep.csv