#!/usr/bin/env bash
#
#Función para buscar lo que quieras. Quita registros de posicion de trampas con base en missin in morfometry
first_file=${1}
first_table=$(basename "${first_file}" .csv)
csvsql --snifflimit 0 --no-inference --blanks --query "
SELECT *
FROM ${first_table}
WHERE Estado_trampa <> 'NA'
" ${first_file} > posicion_trampas_gatos_isla_guadalupe_sNA.csv